name: perfkitbenchmarker # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.5.1-CaptConsternant-repo' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open effort to define & run benchmarks to measure & compare cloud offerings. # 79 char long summary
description: |
  PerfKit Benchmarker is an open effort to define a canonical set of 
  benchmarks to measure and compare cloud offerings. It's designed to operate
  via vendor provided command line tools. The benchmark default settings are 
  not tuned for any particular platform or instance type. These settings are 
  recommended for consistency across services. Only in the rare case where 
  there is a common practice like setting the buffer pool size of a database 
  do we change any settings.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  venv:
    # See 'snapcraft plugins'
    plugin: python
    source-type: local
    source: .
    python-requirements:
      - requirements.txt
      - perfkitbenchmarker/providers/openstack/requirements.txt
      - perfkitbenchmarker/providers/aws/requirements.txt
  source:
    plugin: dump
    source: .


apps:
  run:
    command: bin/python $SNAP/pkb.py
